### ISSUE TITLE
Incorrect npm instructions & Typeos

### ISSUE THREAD

**Issue by TheDevelolper** [eromano/ng2-3d-editor#4]
Hi, just a small note. 

On your npm instructions you put the command: 
npm install --save ng2-**ed**-editor

It should be: 

npm install --save ng2-3d-editor

Thanks!

**Comment by TheDevelolper** [comment]
also notice that you mistyped components in the npm path: 

C:\3dEditor\node_modules\ng2-3d-editor\src\ **componets**

should of course be:
C:\3dEditor\node_modules\ng2-3d-editor\src\components

**Comment by eromano** [comment]
@KiransHub  Thanks I did the change
